Add Filename
nyaruka/courier pull request #356
Opened 2021-04-27 21:49 UTC by rafaelbreno

As said in #353 , I've tested locally and this were the difference:

From:
![WhatsApp Image 2021-04-27 at 18 41 14](https://user-images.githubusercontent.com/32229014/116316559-82654d80-a788-11eb-8f16-20a65109194d.jpeg)

To:
![WhatsApp Image 2021-04-27 at 18 41 13](https://user-images.githubusercontent.com/32229014/116316564-84c7a780-a788-11eb-8bd4-1d0fb2d24662.jpeg)

2021-04-28 16:33 UTC, nicpottier commented
My problem with this is that it's this crazy hack of using the message text as a filename. Do we not know the extension from the attachment name? Can we not use a generic name instead? I really don't think I can go with having the text of a message end up being a filename.

2021-04-28 19:52 UTC, rafaelbreno commented
> My problem with this is that it's this crazy hack of using the message text as a filename. Do we not know the extension from the attachment name? Can we not use a generic name instead? I really don't think I can go with having the text of a message end up being a filename.

I know for sure that we've the `mimeType`, I even thought about creating a helper function to generate the filename using a `uuid4` for the base name, and with the help of as `map[string]string` would be possible to return the file's extension for each case, but it would be a kinda of a long, but the other option would be using the "mediaURL", I'm almost sure that it is the best option. I guess it could be done in 2 ways `regex` or a simple bytes loop, like this:
```
package main

import (
	"fmt"
	"regexp"
	"time"
)

var mediaURL string = "application/pdf:https://some-url.host.service.com/media/999/zz99/9999/da514731-4bed-428c-afb9-860dd94530cc.xlsx"

func main() {
	fmt.Println(reg())
        // da514731-4bed-428c-afb9-860dd94530cc.pdf

	fmt.Println(by())
        // da514731-4bed-428c-afb9-860dd94530cc.pdf

}

func reg() string {
	return regexp.MustCompile(`[a-zA-Z0-9\-]{1,}\.[a-z]{1,4}$`).FindString(mediaURL)
}

func by() string {
	separator := byte('/')
	for i := len(mediaURL) - 1; i >= 0; i-- {
		if mediaURL[i] == separator {
			return mediaURL[i+1:]
		}
	}
	for key, val := range mediaURL {
		fmt.Println(key, string(val), val)
	}
	return ""
}
```

2021-04-29 14:35 UTC, nicpottier commented
You shouldn't need any regexes, these are standard URLs. You can use the standard libraries to get out the path, something like:
  https://play.golang.org/p/_zw3n_TXv0s

2021-04-29 15:19 UTC, rafaelbreno commented
That's pretty good @nicpottier , I didn't know about that method, I think it should be a great option to considerate, for now I'll be doing some benchmarks, between those three, if the performance is a mutual concern, this will be a great way to define, which one to implement:
```
goos: linux
goarch: amd64
BenchmarkReg-8              136411               8506 ns/op
BenchmarkBy-8            42114620                28.5 ns/op
BenchmarkParser-8        1259732                 944 ns/op
PASS
```
The regex one is waaay slower than the others, no regex. 
Using the `by()` function is faster and maybe would need to implement an error handler for it, because I think that all mediaURL will be a URL that returns a static file, so the implemented logic should works on all cases. 
Using the solution that you wrote with the package `net/url` wouldn't need to create an error handler, but it a little slower than the `by()` method.

So Nic, what do you think?

2021-04-29 15:45 UTC, nicpottier commented
This is not something you should be benchmarking, courier is sending messages across a network so none of this matters. You should always pick the simplest, most readable and most correct implementation, which would be the URL version. (there are all sorts of edge cases which your `by()` method likely isn't dealing with (unicode, escape sequences, etc..))

2021-05-06 18:15 UTC, rafaelbreno commented
@nicpottier can you check the update? The only thing isn't clear for me is the way to treat the error, did I implemented it in the way Nyaruka is used to?

2021-05-06 23:04 UTC, nicpottier requested changes

2021-05-06 23:04 UTC, nicpottier commented on utils/misc.go
> +func URLGetFilename(rawURL string) (string, error) {
`BasePathForURL` is probably better.. comment should start with that as well.

2021-05-06 23:04 UTC, nicpottier commented on handlers/whatsapp/whatsapp.go
> +				// Break on erroh
typo

2021-05-06 23:04 UTC, nicpottier commented on handlers/whatsapp/whatsapp.go
> +				logrus.WithField("channel_uuid", msg.Channel().UUID().String()).WithError(err).Error("Erro while parsing the media URL")
typo

2021-05-06 23:04 UTC, nicpottier commented
Couple tweaks but otherwise looks ok.

2021-05-07 14:40 UTC, norkans7 commented on handlers/whatsapp/whatsapp.go
> +				}
I think here you can create a channel log instead for the error and let the error to break on https://github.com/nyaruka/courier/pull/356/files#diff-557153ae44649c16db29083d386ef0de7914adfabb7e118a3b4e019b62a6e48bR525
after we save the logs so users and use can get a chance to see those logs on the web

2021-05-17 10:34 UTC, norkans7 commented on handlers/whatsapp/whatsapp.go
> +				// Break out on error
Adjust the comment

2021-05-17 13:00 UTC, norkans7 commented
@rafaelbreno check the tests are failing

2021-05-17 19:50 UTC, norkans7 approved these changes

2021-05-18 17:18 UTC, merged