Instagram handler
nyaruka/courier pull request #392
Opened 2021-12-17 14:25 UTC by matmsa27

According to [issue](https://github.com/rapidpro/rapidpro/issues/1516) and pr opened on [Rapidpro repository](https://github.com/rapidpro/rapidpro/pull/1596).

2021-12-17 16:32 UTC, norkans7 commented
@matmsa27 I see most codes are copied from the Facebook app channel type?
What challenges are there to use the same app for Facebook and Instagram? 
So the app will need to have all the required permissions for both?

Could that simplify the Instagram handler and possible make a few adjustment to the facebook app one to accommodate that as well?

2021-12-20 14:46 UTC, Robi9 commented
> What challenges are there to using the same app for Facebook and Instagram?

Yes, most of the code is very similar to Facebook. I don't see that it would have a problem to use the same application, it would just leave us stuck in having to use the same for both, we can have rapidpro hosts that are only interested in one of the channels so it would be interesting to have this application distinction.

> So the app will need to have all the required permissions for both?

In case it is just one app for both types, it would be necessary to have all permissions for Facebook and Instagram, but if it is just an app for Instagram, it would not need to have all permissions, it would only be some that the Facebook channel uses and Instagram permissions.

> Could that simplify the Instagram handler and possibly make a few adjustments to the Facebook app one to accommodate that as well?

Could you explain better what you thought about simplifying the Instagram handler if the same app is used for both?

2021-12-20 16:32 UTC, norkans7 commented
@Robi9 I think an approach as the way we handle Twilio types that share a lot of code
https://github.com/nyaruka/courier/blob/main/handlers/twiml/twiml.go#L58

so the Facebookapp type will be the one with the handler but we can initiate the IG channel type are well in the file

all incoming messages will be receive on `/c/fba/receive` and we switch the channel we look for using the payload object value in the request we receive

That way I think we remain with less code so easier to maintain

2021-12-20 17:45 UTC, Robi9 commented
@norkans7 Understood, I will adapt the Facebookapp handler to support the IG type.

2021-12-27 12:26 UTC, Robi9 commented
@norkans7 I decided to separate receiving messages, so Facebook's keep arriving at `c/fba/receive` and Instagram's arrive at `c/ig/receive`, we can do that since the application allows us to indicate callback endpoints for types of different payload objects.

2021-12-28 19:39 UTC, matmsa27 commented
Hi, @norkans7 We are already ready to receive the feedbacks about this PR.

2022-01-03 09:21 UTC, norkans7 commented
@Robi9 good to have two webhooks configured, now I think we need to have the signature validation and webhook validation work for both.
And what is the use of `InstagramApplicationSecret` I think the app will be the same as the facebook one, correct?

2022-01-05 08:00 UTC, norkans7 commented on handlers/facebookapp/facebookapp_test.go
> +		Text: "Simple Message", URN: "facebook:12345",
These tests should us `instagram` URNs

2022-01-05 08:00 UTC, norkans7 commented on handlers/facebookapp/facebookapp_test.go
> +		Text: "Simple Message", URN: "facebook:12345",
not `facebook` URNs

2022-01-05 08:28 UTC, norkans7 requested changes
Adjust the instagram tests

2022-01-05 17:14 UTC, norkans7 commented on handlers/facebookapp/facebookapp.go
> +func newHandler(channelType courier.ChannelType, name string, validateSignatures bool) courier.ChannelHandler {
`validateSignatures` is misleading as that parameter is for using channel UUIDS routes or not

2022-01-05 17:19 UTC, norkans7 commented on handlers/facebookapp/facebookapp_test.go
> +				{"facebook:1337", map[string]string{"name": "John Doe"}},
`instagram` URN

2022-01-05 17:21 UTC, norkans7 commented on handlers/facebookapp/facebookapp_test.go
>  func TestDescribe(t *testing.T) {
I think it is best to have 2 separate tests one for FBA and the other for IG instead of the for loop on a slice of slices and the if condition

2022-01-06 07:27 UTC, norkans7 approved these changes

2022-01-07 18:38 UTC, rowanseymour requested changes

2022-01-07 18:38 UTC, rowanseymour commented on handlers/facebookapp/facebookapp.go
> +	EntryID := payload.Entry[0].ID
`entryID`

2022-01-07 18:38 UTC, rowanseymour commented on handlers/facebookapp/facebookapp_test.go
> +var unkownMessagingEntryFBA = `{
unknown.. not your typo but you can fix while you're here

2022-01-13 14:05 UTC, rowanseymour approved these changes

2022-01-13 14:05 UTC, merged