Quick Replies for VK
nyaruka/courier pull request #394
Opened 2021-12-30 18:06 UTC by Robi9

2022-01-03 10:11 UTC, norkans7 commented on handlers/vk/vk_test.go
> +		QuickReplies: []string{"Yes"},
Can you make the test with many quick replies?

2022-01-03 10:30 UTC, norkans7 commented
This will add all  buttons in one row, I think we need to probably make a new row every 3 buttons or better use the length of the button text to know when to make a new row

2022-01-03 12:27 UTC, Robi9 commented
I did some tests and regardless of the text size, in a new line, 5 buttons are accepted. When the text on these buttons is large, they end up showing a small portion of that text and hiding the rest.

2022-01-03 14:29 UTC, rowanseymour requested changes

2022-01-03 14:29 UTC, rowanseymour commented on handlers/vk/vk.go
> +	b, err := json.Marshal(payload)
I'm fine with not error checking JSON marshalling of things we control - but use `jsonx.MustMarshal`

2022-01-03 14:29 UTC, rowanseymour commented on handlers/vk/vk.go
> +}
this function doesn't feel necessary - use `jsonx.MustMarshal`

2022-01-03 14:29 UTC, rowanseymour commented on handlers/vk/vk.go
> +	}
maybe we can do something similar to the telegram handler and use `utils.StringsToRows` to create better layouts when things don't fit on one row?

2022-01-04 16:10 UTC, Robi9 commented
@rowanseymour I sought the same approach taken for the telegram, it applied well to the VK.

2022-01-05 08:24 UTC, norkans7 approved these changes

2022-01-05 14:20 UTC, rowanseymour approved these changes

2022-01-05 14:20 UTC, merged