Fix receiving attachments in WAC
nyaruka/courier pull request #451
Opened 2022-07-20 21:10 UTC by Robi9

Receiving attachments is not working properly. First, the token used to fetch the media url, channel auth_token, does not exist as WAC channels do not have this token in the channel settings. The token that must be used is the `whatsapp_admin_system_user_token` and in addition, for the media to be downloaded, it is necessary to use the same token.

2022-07-21 12:24 UTC, norkans7 commented on handlers/facebookapp/facebookapp.go
> +					mediaURL, err = resolveMediaURL(channel, msg.Audio.ID, token)
I think channel is not needed in this case, so remove that parameter

2022-07-21 13:48 UTC, norkans7 approved these changes

2022-07-21 14:55 UTC, rowanseymour requested changes

2022-07-21 14:55 UTC, rowanseymour commented on backends/rapidpro/msg.go
> +	if channel.ChannelType() == "WAC" {
backend shouldn't know about specific channel types - can't this be set in `BuildDownloadMediaRequest` ?

2022-07-22 21:13 UTC, norkans7 approved these changes

2022-07-25 14:28 UTC, rowanseymour approved these changes

2022-07-25 14:28 UTC, merged