Integration support with Microsoft Teams
nyaruka/courier pull request #455
Opened 2022-07-26 14:26 UTC by Robi9

https://github.com/rapidpro/rapidpro/issues/1661

2022-08-19 10:45 UTC, norkans7 commented on handlers/teams/teams.go
> +	jv                          = JwtTokenValidator{}
better be called `jwtTokenValidator` instead of `jv`

2022-08-19 10:47 UTC, norkans7 commented on handlers/teams/teams.go
> +	jwks_uri                    = "https://login.botframework.com/v1/.well-known/keys"
camel case here `jwtKeysURI`

2022-08-19 10:48 UTC, norkans7 commented on handlers/teams/teams.go
> +	jwks_uri                    = "https://login.botframework.com/v1/.well-known/keys"
or `jwksURI` probably

2022-08-19 11:09 UTC, norkans7 commented on handlers/teams/teams.go
> +	AadObjectId      string `json:"aadObjectId"`
ID should be in uppercase and all other acronym such as URL too

2022-08-19 11:10 UTC, norkans7 commented on handlers/teams/teams.go
> +	AadObjectId      string `json:"aadObjectId"`
`ContentURL`, `ServiceURL`, `ChannelID`, ...

2022-08-19 11:22 UTC, norkans7 commented on handlers/teams/teams.go
> +		act.Text = "Create Conversation"
This is going to be saved as a message text?
Is that what we need here?

2022-08-19 11:24 UTC, norkans7 commented on handlers/teams/teams_test.go
> +var defaultSendTestCases = []ChannelSendTestCase{
Can you add error case test as well?

2022-08-19 11:25 UTC, norkans7 commented on handlers/teams/teams_test.go
> +	{
what should the text be in these cases?

2022-08-19 11:28 UTC, norkans7 requested changes
You need to update these changes to use the same logger approach as in https://github.com/nyaruka/courier/pull/477/files

2022-08-29 14:16 UTC, matmsa27 commented
Hi @norkans7 any updates on this review? tks

2022-09-13 15:00 UTC, matmsa27 commented
Hey, @rowanseymour @norkans7 any news on this PR?

2024-02-15 13:41 UTC, closed without merging