Add support for sending interactive messages with attachments, quick replies and captions in WAC
nyaruka/courier pull request #497
Opened 2022-09-06 15:12 UTC by Robi9

@norkans7 Here's the part of the other PR that deals with interactive messages.

2022-09-08 20:28 UTC, norkans7 requested changes

2022-10-18 15:56 UTC, rowanseymour commented
@Robi9 @matmsa27 would be nice to get this merged. Just needs conflicts resolved.

2022-10-18 17:18 UTC, Robi9 commented
I have read the CLA Document and I hereby sign the CLA

2022-10-18 19:22 UTC, norkans7 approved these changes

2022-10-19 14:27 UTC, merged