Prep for support for more WA templates components
nyaruka/courier pull request #664
Opened 2023-11-29 21:49 UTC by norkans7

2023-11-30 11:29 UTC, norkans7 commented on handlers/meta/whatsapp/templates.go
> +		for _, v := range templating.Variables {
I kept supporting the templating variables so this can be deployed even if the goflow changes are not yet done

2023-11-30 11:30 UTC, norkans7 commented on handlers/meta/whatsapp/templates.go
> +func GetTemplatePayload(templating MsgTemplating, lang string) *Template {
I used this method to keep the code DRY between WAC and D3C channels

2023-11-30 11:31 UTC, norkans7 commented on handlers/whatsapp_legacy/handler.go
> +					component := &Component{Type: "body"}
Just body to keep the same features but no new components supported for legacy WA channels

2024-01-15 15:34 UTC, rowanseymour requested changes

2024-01-15 15:34 UTC, rowanseymour commented on handlers/whatsapp_legacy/handler.go
> +	} `json:"params"`
let's call this `parameters` to match the meta side of things

2024-01-15 16:33 UTC, merged