Std Error part 2
nyaruka/courier pull request #748
Opened 2024-05-21 15:47 UTC by norkans7

2024-05-21 15:48 UTC, norkans7 commented
We need to update `github.com/nyaruka/redisx` to completely remove `github.com/pkg/errors`

2024-05-30 13:20 UTC, rowanseymour commented on handlers/yo/handler.go
> +	"errors"
no space above

2024-05-30 13:20 UTC, rowanseymour commented on handlers/whatsapp_legacy/handler.go
> +	"errors"
no space above

2024-05-30 13:21 UTC, rowanseymour requested changes

2024-06-03 17:59 UTC, merged